name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: python -m unittest test_app.py 